import AnimatedTxt from "@/components/AnimatedTxt";
import HireMe from "@/components/HireMe";
import { FullStackCircularLogo, LinkArrow } from "@/components/Icons";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import birne from "../../public/images/hero/birne.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex items-center jestify-between w-full">
            <div className="w-1/3 p-5">
              <Image
                src={birne}
                alt="inTech light bulb"
                className="w-full h-auto rounded-full"
              />
            </div>
            <div className="w-2/3 flex flex-col items-center self-center">
              <AnimatedTxt
                text="Turning Vision Into Reality With Code And Design."
                className="text-5xl"
              />

              <p className="my-4 ml-6 px-2 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web and mobile applications. Explore my
                latest own projects and solutions for customers, showcasing my
                expertise in React.js, Next.js, tRPC, Prisma, Node.js,
                React-Native, GraphQL and more.
              </p>
              <div className="flex items-center self-start my-4 ml-6 px-2 ">
                <Link
                  href="/solutions"
                  className="flex items-center bg-dark text-light p-3.5 px-6 rounded-lg text-lg font-semibold hover:bg-slate-800"
                >
                  Explore Solutions
                  <LinkArrow className={"w-5 ml-2 mb-[2px]"} />
                </Link>
                <Link
                  href="mailto:gero.walther@gmail.com"
                  className="ml-8 text-lg font-medium caption-top text-dark underline underline-offset-8"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
